export const GET_FORECAST_DATA_REQUEST = 'auth/GET_FORECAST_DATA_REQUEST';
export const GET_FORECAST_DATA_SUCCESS = 'auth/GET_FORECAST_DATA_SUCCESS';
export const GET_FORECAST_DATA_FAILURE = 'auth/GET_FORECAST_DATA_FAILURE';
